
name: Validar sintaxis de scripts SQL

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'src/*.sql'
      - '*.txt'
      - '.github/workflows/revisar_sintaxis.yml'
  workflow_dispatch:

jobs:
  revisar-sintaxis:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Validar sintaxis de scripts listados
        run: |
          SCRIPT_FILE="scripts_dev.txt"

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            SCRIPT_FILE="scripts_pro.txt"
          fi

          echo "🔍 Validando sintaxis de scripts listados en $SCRIPT_FILE"

          if [ ! -f "$SCRIPT_FILE" ]; then
            echo "❌ No se encontró el archivo: $SCRIPT_FILE"
            exit 1
          fi

          errores=0

          while IFS= read -r script || [ -n "$script" ]; do
            if [ ! -f "src/$script" ]; then
              echo "❌ Script no encontrado: src/$script"
              errores=$((errores+1))
              continue
            fi

            echo "🔎 Analizando src/$script..."
            sqlfluff lint "src/$script"
            if [ $? -ne 0 ]; then
              echo "❌ Errores de sintaxis en: src/$script"
              errores=$((errores+1))
            else
              echo "✅ Sintaxis correcta: src/$script"
            fi
          done < "$SCRIPT_FILE"

          if [ $errores -ne 0 ]; then
            echo "❌ Se encontraron errores de sintaxis en $errores scripts."
            exit 1
          fi

          echo "🎉 Todos los scripts tienen sintaxis válida."
