name: "Postgres_Pre_Pro - SQL Deployment"

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'src/instruccionesPRE.txt'
      - 'src/*.sql'
      - 'src/scripts*.txt'

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Establecer variables de entorno por rama
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "entorno=PRO" >> $GITHUB_OUTPUT
            echo "script_file=scripts_pro.txt" >> $GITHUB_OUTPUT
          else
            echo "entorno=DEV" >> $GITHUB_OUTPUT
            echo "script_file=scripts_dev.txt" >> $GITHUB_OUTPUT
          fi

      - name: Verificar carga de secrets (sin revelar datos)
        env:
          PGHOST: ${{ secrets[format('PGHOST_{0}', steps.vars.outputs.entorno)] }}
          PGUSER: ${{ secrets[format('PGUSER_{0}', steps.vars.outputs.entorno)] }}
          PGPASSWORD: ${{ secrets[format('PGPASSWORD_{0}', steps.vars.outputs.entorno)] }}
          PGPORT: ${{ secrets[format('PGPORT_{0}', steps.vars.outputs.entorno)] }}
          PGDATABASE: ${{ secrets[format('PGDATABASE_{0}', steps.vars.outputs.entorno)] }}
        run: |
          echo "✔️ Secrets cargados para entorno: ${{ steps.vars.outputs.entorno }}"

      - name: Probar conexión a la base de datos
        env:
          PGHOST: ${{ secrets[format('PGHOST_{0}', steps.vars.outputs.entorno)] }}
          PGPORT: ${{ secrets[format('PGPORT_{0}', steps.vars.outputs.entorno)] }}
          PGUSER: ${{ secrets[format('PGUSER_{0}', steps.vars.outputs.entorno)] }}
          PGPASSWORD: ${{ secrets[format('PGPASSWORD_{0}', steps.vars.outputs.entorno)] }}
          PGDATABASE: ${{ secrets[format('PGDATABASE_{0}', steps.vars.outputs.entorno)] }}
        run: |
          psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c '\conninfo'

      - name: Ejecutar scripts listados
        env:
          PGHOST: ${{ secrets[format('PGHOST_{0}', steps.vars.outputs.entorno)] }}
          PGPORT: ${{ secrets[format('PGPORT_{0}', steps.vars.outputs.entorno)] }}
          PGUSER: ${{ secrets[format('PGUSER_{0}', steps.vars.outputs.entorno)] }}
          PGPASSWORD: ${{ secrets[format('PGPASSWORD_{0}', steps.vars.outputs.entorno)] }}
          PGDATABASE: ${{ secrets[format('PGDATABASE_{0}', steps.vars.outputs.entorno)] }}
        run: |
          while IFS= read -r script; do
            echo "🚀 Ejecutando src/$script"
            psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -f "src/$script"
          done < "src/${{ steps.vars.outputs.script_file }}"

      - name: Notificación al finalizar
        run: echo "✅ Despliegue completado con éxito en entorno ${{ steps.vars.outputs.entorno }}"

