name: "Postgres_Pre_Pro - SQL Deployment"

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'src/**/*.sql'
      - 'src/**/*.txt'
      - '.github/**/*.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jmontalvof/postgres-ia-runner:latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Establecer variables de entorno por rama
        id: variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "host=${{ secrets.POSTGR_HOST_PRO }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.POSTGR_USER_PRO }}" >> $GITHUB_OUTPUT
            echo "password=${{ secrets.POSTGR_PASSWORD_PRO }}" >> $GITHUB_OUTPUT
            echo "port=${{ secrets.POSTGR_PORT_PRO }}" >> $GITHUB_OUTPUT
            echo "database=${{ secrets.POSTGR_DATABASE_PRO }}" >> $GITHUB_OUTPUT
            echo "script_file=scripts.txt" >> $GITHUB_OUTPUT
          else
            echo "host=${{ secrets.POSTGR_HOST_DEV }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.POSTGR_USER_DEV }}" >> $GITHUB_OUTPUT
            echo "password=${{ secrets.POSTGR_PASSWORD_DEV }}" >> $GITHUB_OUTPUT
            echo "port=${{ secrets.POSTGR_PORT_DEV }}" >> $GITHUB_OUTPUT
            echo "database=${{ secrets.POSTGR_DATABASE_DEV }}" >> $GITHUB_OUTPUT
            echo "script_file=scripts_dev.txt" >> $GITHUB_OUTPUT
          fi

      - name: Ejecutar scripts listados (con autocorrección IA si falla)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for script in $(cat src/${{ steps.variables.outputs.script_file }}); do
            echo "🚀 Ejecutando src/$script"
            if ! PGPASSWORD=${{ steps.variables.outputs.password }} psql -h "${{ steps.variables.outputs.host }}" \
                -p "${{ steps.variables.outputs.port }}" -U "${{ steps.variables.outputs.user }}" \
                -d "${{ steps.variables.outputs.database }}" -f "src/$script"; then

              echo "⚠️ Error al ejecutar $script. Enviando a IA para corregir..."
              python fix_sql.py --error "Error al ejecutar $script" --file "src/$script"

              echo "🔁 Reintentando con src/${script%.sql}_fix.sql"
              if PGPASSWORD=${{ steps.variables.outputs.password }} psql -h "${{ steps.variables.outputs.host }}" \
                  -p "${{ steps.variables.outputs.port }}" -U "${{ steps.variables.outputs.user }}" \
                  -d "${{ steps.variables.outputs.database }}" -f "src/${script%.sql}_fix.sql"; then
                echo "🎯 ChatGPT corrigió el script y se ejecutó con éxito: ${script%.sql}_fix.sql"
              else
                echo "❌ El script corregido también falló: ${script%.sql}_fix.sql"
                exit 1
              fi
            fi
          done
