name: "Despliegue SQL con autocorrección IA"

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'src/*.sql'
      - 'src/*.txt'
      - '.github/workflows/deploy-sql.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jmontalvof/postgres-ia-runner:latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Verificar script de autocorrección
        run: |
          ls -la fix_sql.py
          chmod +x fix_sql.py

      - name: Cargar variables de entorno
        id: variables
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "entorno=PRO" >> $GITHUB_OUTPUT
            echo "script_file=scripts_pro.txt" >> $GITHUB_OUTPUT
            echo "host=${{ secrets.PGHOST_PRO }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.PGUSER_PRO }}" >> $GITHUB_OUTPUT
            echo "password=${{ secrets.PGPASSWORD_PRO }}" >> $GITHUB_OUTPUT
            echo "port=${{ secrets.PGPORT_PRO }}" >> $GITHUB_OUTPUT
            echo "database=${{ secrets.PGDATABASE_PRO }}" >> $GITHUB_OUTPUT
          else
            echo "entorno=DEV" >> $GITHUB_OUTPUT
            echo "script_file=scripts_dev.txt" >> $GITHUB_OUTPUT
            echo "host=${{ secrets.PGHOST_DEV }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.PGUSER_DEV }}" >> $GITHUB_OUTPUT
            echo "password=${{ secrets.PGPASSWORD_DEV }}" >> $GITHUB_OUTPUT
            echo "port=${{ secrets.PGPORT_DEV }}" >> $GITHUB_OUTPUT
            echo "database=${{ secrets.PGDATABASE_DEV }}" >> $GITHUB_OUTPUT
          fi

      - name: Ejecutar scripts listados (con autocorrección IA si falla)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for script in $(cat src/${{ steps.variables.outputs.script_file }}); do
            echo "🚀 Ejecutando src/$script"
            if ! PGPASSWORD=${{ steps.variables.outputs.password }} psql -h "${{ steps.variables.outputs.host }}" \
                -p "${{ steps.variables.outputs.port }}" -U "${{ steps.variables.outputs.user }}" \
                -d "${{ steps.variables.outputs.database }}" -f "src/$script"; then

              echo "⚠️ Error al ejecutar $script. Enviando a IA para corregir..."
              python fix_sql.py --error "Error al ejecutar $script" --file "src/$script"

              echo "🔁 Reintentando con src/${script%.sql}_fix.sql"
              if PGPASSWORD=${{ steps.variables.outputs.password }} psql -h "${{ steps.variables.outputs.host }}" \
                  -p "${{ steps.variables.outputs.port }}" -U "${{ steps.variables.outputs.user }}" \
                  -d "${{ steps.variables.outputs.database }}" -f "src/${script%.sql}_fix.sql"; then
                echo "🎯 Script corregido ejecutado con éxito: ${script%.sql}_fix.sql"
              else
                echo "❌ Falló incluso con el script corregido: ${script%.sql}_fix.sql"
                exit 1
              fi
            fi
          done
