
name: Validar y Ejecutar SQL

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  validar_y_ejecutar:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ github.ref == 'refs/heads/main' && secrets.PGDATABASE_PROD || secrets.PGDATABASE_DEV }}
      DB_USER: ${{ github.ref == 'refs/heads/main' && secrets.PGUSER_PROD || secrets.PGUSER_DEV }}
      DB_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.PGPASSWORD_PROD || secrets.PGPASSWORD_DEV }}
      DB_HOST: ${{ github.ref == 'refs/heads/main' && secrets.PGHOST_PROD || secrets.PGHOST_DEV }}
      DB_PORT: ${{ github.ref == 'refs/heads/main' && secrets.PGPORT_PROD || secrets.PGPORT_DEV }}
      GITHUB_REF: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Validar y ejecutar scripts
        run: python main.py
