
name: Validar sintaxis de scripts SQL

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'src/*.sql'
      - '*.txt'
      - '.github/workflows/revisar_sintaxis.yml'
  workflow_dispatch:

jobs:
  revisar-sintaxis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Validar sintaxis de scripts listados
        run: |
          SCRIPT_FILE="scripts_DEV.txt"
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            SCRIPT_FILE="scripts_PRO.txt"
          fi

          echo "🔍 Validando sintaxis de los scripts en $SCRIPT_FILE"
          if [ ! -f "$SCRIPT_FILE" ]; then
            echo "❌ No se encontró el archivo: $SCRIPT_FILE"
            exit 1
          fi

          errores=0
          while IFS= read -r script || [ -n "$script" ]; do
            if [ ! -f "$script" ]; then
              echo "❌ Script no encontrado: $script"
              errores=$((errores+1))
              continue
            fi

            echo "🔎 Validando $script..."
            sqlfluff lint "$script"
            if [ $? -ne 0 ]; then
              echo "❌ Errores de sintaxis en $script"
              errores=$((errores+1))
            else
              echo "✅ Sintaxis válida: $script"
            fi
          done < "$SCRIPT_FILE"

          if [ $errores -ne 0 ]; then
            echo "❌ Se encontraron errores de sintaxis en $errores scripts."
            exit 1
          fi

          echo "🎉 Todos los scripts tienen sintaxis válida."
